name: Advanced Workflow

# triggers for the workflow, branches to apply workflow
# e.g., on: [push, pull_request, workflow_dispatch, scheduled, fork, issue]
on:
  workflow_dispatch:

jobs:
  first_job:
    # define runner with 'runs-on'
    runs-on: ubuntu-latest
    steps:
      - name:  First Job Script
        shell: bash
        run:   echo Hello World!  This is the first Job.
      # checkout from target branch
      - name: Checkout Action
        uses: actions/checkout@v6
      # from javascript hello world action
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
            echo "The time of the greeting was ${{ steps.print-to-log.outputs.time }}"



  second_job:
    # define runner with 'runs-on'
    runs-on: ubuntu-latest
    steps:
      - name:  Second Job Script
        shell: bash
        run:   |
          echo This is the Second Job Script
          echo This is a Multi-line Script

  
